/* Generated By:JavaCC: Do not edit this line. JJTest2Constants.java */
package com.delligattiassociates.jct.test.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JJTest2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_COMMENT = 6;
  /** RegularExpression Id. */
  int K_NAMESPACE = 11;
  /** RegularExpression Id. */
  int K_PACKAGE = 12;
  /** RegularExpression Id. */
  int K_COMMENT = 13;
  /** RegularExpression Id. */
  int K_ABOUT = 14;
  /** RegularExpression Id. */
  int K_IMPORT = 15;
  /** RegularExpression Id. */
  int K_BLOCK = 16;
  /** RegularExpression Id. */
  int K_ALIAS = 17;
  /** RegularExpression Id. */
  int K_AS = 18;
  /** RegularExpression Id. */
  int K_FEATURE = 19;
  /** RegularExpression Id. */
  int K_CLASS = 20;
  /** RegularExpression Id. */
  int K_PRIVATE = 21;
  /** RegularExpression Id. */
  int K_PUBLIC = 22;
  /** RegularExpression Id. */
  int K_QUIT = 23;
  /** RegularExpression Id. */
  int O_COLON = 24;
  /** RegularExpression Id. */
  int O_SCOPE = 25;
  /** RegularExpression Id. */
  int O_SPLAT = 26;
  /** RegularExpression Id. */
  int T_LBRACE = 27;
  /** RegularExpression Id. */
  int T_RBRACE = 28;
  /** RegularExpression Id. */
  int T_IDENTIFIER = 29;
  /** RegularExpression Id. */
  int T_NONSPACE_IDENTIFIER = 30;
  /** RegularExpression Id. */
  int LETTER = 31;
  /** RegularExpression Id. */
  int DIGIT = 32;
  /** RegularExpression Id. */
  int T_SCOPED_IDENTIFIER = 33;
  /** RegularExpression Id. */
  int T_SPACE_IDENTIFIER = 34;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"//\"",
    "\"/*\"",
    "\"\\n\"",
    "<token of kind 8>",
    "\"*/\"",
    "<token of kind 10>",
    "\"namespace\"",
    "\"package\"",
    "\"comment\"",
    "\"about\"",
    "\"import\"",
    "\"block\"",
    "\"alias\"",
    "\"as\"",
    "\"feature\"",
    "\"class\"",
    "\"private\"",
    "\"public\"",
    "\"quit\"",
    "\":\"",
    "\"::\"",
    "\"*\"",
    "\"{\"",
    "\"}\"",
    "<T_IDENTIFIER>",
    "<T_NONSPACE_IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<T_SCOPED_IDENTIFIER>",
    "<T_SPACE_IDENTIFIER>",
    "\";\"",
  };

}
